export const MOROCCO_CITIES = [
  "Agadir",
  "Ait Melloul",
  "Al Hoceima",
  "Aousserd",
  "Asilah",
  "Azemmour",
  "Azilal",
  "Beni Mellal",
  "Ben Guerir",
  "Benslimane",
  "Berkane",
  "Berrechid",
  "Bouarfa",
  "Boujdour",
  "Boulemane",
  "Bouznika",
  "Casablanca",
  "Chefchaouen",
  "Chichaoua",
  "Dakhla",
  "Demnate",
  "Driouch",
  "El Hajeb",
  "El Jadida",
  "El Kelaa des Sraghna",
  "Errachidia",
  "Essaouira",
  "Fes",
  "Fquih Ben Salah",
  "Fnideq",
  "Guelmim",
  "Guercif",
  "Ifrane",
  "Inezgane",
  "Jerada",
  "Kalaat Mgouna",
  "Kasba Tadla",
  "Khemisset",
  "Khenifra",
  "Khouribga",
  "Ksar El Kebir",
  "Laayoune",
  "Larache",
  "Marrakesh",
  "Martil",
  "M'diq",
  "Meknes",
  "Midelt",
  "Mohammedia",
  "Nador",
  "Ouarzazate",
  "Ouezzane",
  "Oujda",
  "Rabat",
  "Safi",
  "Sale",
  "Sefrou",
  "Settat",
  "Sidi Bennour",
  "Sidi Ifni",
  "Sidi Kacem",
  "Sidi Slimane",
  "Skhirate",
  "Smara",
  "Souk El Arbaa",
  "Tan-Tan",
  "Tangier",
  "Taounate",
  "Taourirt",
  "Tarfaya",
  "Taroudant",
  "Taza",
  "Temara",
  "Tetouan",
  "Tinghir",
  "Tiznit",
  "Youssoufia",
  "Zagora",

  // Extra commonly used towns (helps “all cities” feel)
  "Ait Ourir",
  "Al Aaroui",
  "Aourir",
  "Arfoud",
  "Bab Berred",
  "Ben Ahmed",
  "Ben Slimane",
  "Beni Ansar",
  "Bni Bouayach",
  "Bni Chiker",
  "Bouznika",
  "Dar Bouazza",
  "El Aioun Sidi Mellouk",
  "El Guerdan",
  "El Ouatia",
  "Imzouren",
  "Khenichet",
  "Lqliaa",
  "Mehdia",
  "Oualidia",
  "Oulad Teima",
  "Oulad Tayeb",
  "Oulad Yaich",
  "Rissani",
  "Sabaa Aiyoun",
  "Saidia",
  "Sidi Yahya El Gharb",
  "Sidi Bouknadel",
  "Tamesna",
  "Tafraout",
  "Taza",
  "Zemamra"
];

export const CITY_DATALIST_ID = "moroccoCities";

export function cityDatalistHtml() {
  const opts = MOROCCO_CITIES.map((c) => `<option value="${String(c).replaceAll('"', "&quot;")}"></option>`).join(
    ""
  );
  return `<datalist id="${CITY_DATALIST_ID}">${opts}</datalist>`;
}

